/*
 * File: app/view/patientForm.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.view.patientForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientForm',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.Select',
        'Ext.field.Toggle',
        'Ext.Map',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        layout: 'vbox',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'fieldset',
                title: 'patientform',
                items: [
                    {
                        xtype: 'numberfield',
                        label: 'Patient Id',
                        name: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        height: '80%',
                        label: 'Disease',
                        options: [
                            {
                                text: 'Malaria',
                                value: 'malaria'
                            },
                            {
                                text: 'Dengue',
                                value: 'dengue'
                            },
                            {
                                text: 'Typhiod',
                                value: 'typhiod'
                            }
                        ]
                    },
                    {
                        xtype: 'togglefield',
                        height: '60%',
                        label: 'Emergency',
                        name: 'Emergency',
                        activeLabel: 'Yes',
                        inactiveLabel: 'No'
                    },
                    {
                        xtype: 'togglefield',
                        height: 60,
                        label: 'Location',
                        name: 'location'
                    },
                    {
                        xtype: 'map',
                        height: 250,
                        itemId: 'newLocationMap'
                    },
                    {
                        xtype: 'textareafield',
                        height: 60,
                        label: 'Additional Information',
                        name: 'info',
                        placeHolder: 'Enter your symptoms/condition'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'patientButton',
                ui: 'confirm',
                text: 'Add Location'
            }
        ]
    }

});